language: python
python:
  - "2.7"
env:
  - IGNORE_POSTGRES=1
  - IGNORE_MYSQL=1
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-test.txt"
script: "python setup.py test"